#!/usr/bin/env ruby -wKU
require 'fileutils'

if ARGV.length < 1 || !File.exists?(ARGV.first)
  puts "usage: sweep <path>"
  exit 1
end

SWEEP_PATH = ARGV.first

class Fixnum
  def minute; self * 60;         end; def minutes; minute; end
  def hour;   self * 60.minutes; end; def hours;   hour;   end
  def day;    self * 24.hours;   end; def days;    day;    end
  def week;   self * 7.days;     end; def weeks;   week;   end
  def month;  self * 30.days;    end; def months;  month;  end
end

SWEEPERS = {
  '_Day'   => 1.day,
  '_Week'  => 1.week,
  '_Month' => 1.month,
  '_Trash' => 2.months
}

def sweep(path)

  sweepers_by_path = {}
  sweepers_by_interval = []

  SWEEPERS.each do |sweeper, interval|
    sweeper_path = File.join(SWEEP_PATH, sweeper)
    FileUtils.mkdir_p(sweeper_path)
    sweepers_by_path[sweeper_path] = interval
    sweepers_by_interval << [interval, sweeper_path]
  end

  sweepers_by_interval = sweepers_by_path.to_a.sort_by { |s| s[1] }.reverse

  Dir[File.join(path, '*')].each do |file|
    next if sweepers_by_path[file]
    atime = File.new(file).atime
    sweepers_by_interval.each do |sweeper, interval|
      if (Time.now - interval) > atime
        File.rename(file, File.join(sweeper, File.basename(file)))
        break
      end
    end
  end
  
end

sweep(SWEEP_PATH)
SWEEPERS.each do |sweeper, interval|
  sweep(File.join(SWEEP_PATH, sweeper))
end